# Generated by Django 4.1.2 on 2022-10-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reference_number',
            field=models.CharField(max_length=100),
        ),
    ]
