# Generated by Django 4.1.2 on 2022-10-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_request_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='author',
        ),
    ]
