# Generated by Django 3.2.8 on 2022-11-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_request_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
