# Generated by Django 3.2.8 on 2022-11-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221106_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateField(),
        ),
    ]
