# Generated by Django 4.0.2 on 2022-11-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20221106_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.TextField(),
        ),
    ]
