# Generated by Django 4.0.2 on 2022-11-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_request_deadline_alter_request_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
