# Generated by Django 4.0.2 on 2022-11-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_request_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Proposed'), ('3', 'Interview'), ('4', 'Results won'), ('5', 'Results lost'), ('6', 'No resource')], default='3', max_length=10),
        ),
    ]
