# Generated by Django 4.0.2 on 2022-11-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Proposed'), ('3', 'Interview'), ('4', 'Results won'), ('5', 'Results lost'), ('6', 'No resource')], default='1', max_length=10),
        ),
    ]
